OverlapScoreThr: 0.5
VoxelSizeForOverlapCalc: 0.5
NumPrKeyPtFactor: 6
PlaneInlinerRatioThr: 0.4
AdjKPFCov: [0.000001, 0.000001, 0.000001]
LCKPFCov: [0.01, 0.01, 0.01]
MargFCov: [0.000001, 0.000001, 0.000001, 0.0001, 0.0001, 0.0001]
SavePCD: false
PCDSaveStep: 10
PubCorrectedMap: false  ## Online pub corrected full map with a frequency
